/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resumebuilder;
import java.util.*;
import javax.swing.*;
import java.awt.event.*;
import java.io.File;
import java.awt.*;
/**
 *
 * @author DELL
 */
public class ResumeUI extends javax.swing.JFrame implements ActionListener{
public JLabel l,l1,l2,l3,l4,l5,l6,l7,l8;
	public JTextField t1,t2,t3,t4,t5,t6;
	public JButton b1,b2;
	public Font f;
	public String ImagePath;
	
	public ResumeUI() {
		f = new Font("SansSerif", Font.BOLD, 20);
		l = new JLabel("Personal Details");
		l.setFont(f);
		l8 = new JLabel("");
		l8.setIcon(new ImageIcon("/Users/harshith/eclipse-workspace/ResumeBuilder/src/placeholder-200x200.png"));
		l1 = new JLabel("Name");
		l2 = new JLabel("Date Of Birth");
		l3 = new JLabel("Father Name");
		l4 = new JLabel("Nationality");
		l5 = new JLabel("Phone Number");
		l6 = new JLabel("Email ID");
		t1 = new JTextField();
		t2 = new JTextField();
		t3 = new JTextField();
		t4 = new JTextField();
		t5 = new JTextField();
		t6 = new JTextField();
		b1 = new JButton("Education -->");
		b2 = new JButton("Browse ...");
		l.setBounds(150, 10, 250,50);
		l1.setBounds(50,90,100,40);
		l2.setBounds(50,130,100,40);
		l3.setBounds(50,170,100,40);
		l4.setBounds(50,210,100,40);
		l5.setBounds(50,250,100,40);
		l6.setBounds(50,290,100,40);
		l8.setBounds(450, 10, 400,400);
		t1.setBounds(200,90,200,40);
		t2.setBounds(200,130,200,40);
		t3.setBounds(200,170,200,40);
		t4.setBounds(200,210,200,40);
		t5.setBounds(200,250,200,40);
		t6.setBounds(200,290,200,40);
		b1.setBounds(600,400,130,50);
		b2.setBounds(490, 320, 110,30);
		add(l);
		add(l1);
		add(l2);
		add(l3);
		add(l4);
		add(l5);
		add(l8);
		add(l6);
		add(t1);
		add(t2);
		add(t3);
		add(t4);
		add(t5);
		add(t6);
		add(b1);
		add(b2);
		b1.addActionListener(this);
		b2.addActionListener(this);
		setLayout(null);
		setVisible(true);
		setSize(800,500);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		if((e.getSource())==b1) {
			new EducationUI(t1.getText(),t2.getText(),t3.getText(),t4.getText(),t5.getText(),t6.getText(),this.ImagePath);
		}
		else{
			FileBrowser f = new FileBrowser();
			if(f.getAbsolutePath()!=null) {
				this.ImagePath=f.getAbsolutePath();
				ImageIcon icon = new ImageIcon(f.getAbsolutePath());
				Image scaleImage = icon.getImage().getScaledInstance(200, 200,Image.SCALE_DEFAULT);
				l8.setIcon(new ImageIcon(scaleImage));
			}
		}
	}
    /**
     * Creates new form ResumeUI
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
